services:
  blogsmicroservice:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/blogsmicroservice
    command: /bin/sh -c "python manage.py init_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=blogsmicroservice_db
      - DB_USER=root
      - DB_PASSWORD=root

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-volume: